"""add ticker_source to tickers

Revision ID: 1234f049eb54
Revises: e6d88fcf0798
Create Date: 2026-05-03 11:31:52.034694

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1234f049eb54'
down_revision: str | None = 'e6d88fcf0798'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'ticker_source',
                sa.String(length=16),
                nullable=False,
                server_default='watchlist',
            )
        )
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.alter_column('ticker_source', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.drop_column('ticker_source')

    # ### end Alembic commands ###
