"""initial schema

Revision ID: 516eb43cb94b
Revises: 
Create Date: 2026-05-01 20:07:23.254038

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '516eb43cb94b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_preferences',
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('alert_type')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channels_sent', sa.Text(), nullable=True),
    sa.Column('user_acked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('filter_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)

    op.create_table('macro_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vix_close', sa.Float(), nullable=True),
    sa.Column('vix_9d', sa.Float(), nullable=True),
    sa.Column('vix_term_structure', sa.Float(), nullable=True),
    sa.Column('spy_close', sa.Float(), nullable=True),
    sa.Column('spy_ema_200', sa.Float(), nullable=True),
    sa.Column('spy_above_200ema', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['filter_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bars_daily',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    with op.batch_alter_table('bars_daily', schema=None) as batch_op:
        batch_op.create_index('ix_bars_daily_symbol_date_desc', ['symbol', 'date'], unique=False)

    op.create_table('earnings',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=False),
    sa.Column('time_of_day', sa.String(length=16), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'earnings_date')
    )
    op.create_table('indicators_daily',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('ema_200_weekly', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_mid', sa.Float(), nullable=True),
    sa.Column('iv_atm', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('iv_percentile', sa.Float(), nullable=True),
    sa.Column('hv_20', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('options_snapshot',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'expiration', 'strike', 'option_type')
    )
    op.create_table('position_legs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('leg_type', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_legs_position_id'), ['position_id'], unique=False)

    op.create_table('position_snapshots',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('option_mid', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('pct_max_profit', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'snapshot_at')
    )
    op.create_table('screener_results',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('filter_results_json', sa.JSON(), nullable=True),
    sa.Column('target_strike', sa.Float(), nullable=True),
    sa.Column('target_expiration', sa.Date(), nullable=True),
    sa.Column('target_premium', sa.Float(), nullable=True),
    sa.Column('target_delta', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['filter_configs.id'], ),
    sa.PrimaryKeyConstraint('date', 'symbol', 'config_id')
    )
    op.create_table('backtest_equity',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('collateral_locked', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'date')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('leg_type', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_trades_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_run_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_trades_cycle_id'))

    op.drop_table('backtest_trades')
    op.drop_table('backtest_equity')
    op.drop_table('screener_results')
    op.drop_table('position_snapshots')
    with op.batch_alter_table('position_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_legs_position_id'))

    op.drop_table('position_legs')
    op.drop_table('options_snapshot')
    op.drop_table('indicators_daily')
    op.drop_table('earnings')
    with op.batch_alter_table('bars_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_bars_daily_symbol_date_desc')

    op.drop_table('bars_daily')
    op.drop_table('backtest_runs')
    op.drop_table('tickers')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_cycle_id'))

    op.drop_table('positions')
    op.drop_table('macro_daily')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    op.drop_table('filter_configs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_symbol'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    op.drop_table('alert_preferences')
    # ### end Alembic commands ###
